/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedLerQrRouteImport } from './routes/_authenticated/ler-qr'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as AuthenticatedDestinosIndexRouteImport } from './routes/_authenticated/destinos/index'
import { Route as AuthenticatedDestinosNovoRouteImport } from './routes/_authenticated/destinos/novo'
import { Route as AuthenticatedPlacasIndexRouteImport } from './routes/_authenticated/placas/index'
import { Route as AuthenticatedPlacasNovaRouteImport } from './routes/_authenticated/placas/nova'
import { Route as AuthenticatedPlacasCodeConfigurarRouteImport } from './routes/_authenticated/placas/$code.configurar'
import { Route as AuthenticatedPlacasCodeQrRouteImport } from './routes/_authenticated/placas/$code.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLerQrRoute = AuthenticatedLerQrRouteImport.update({
  id: '/ler-qr',
  path: '/ler-qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDestinosIndexRoute =
  AuthenticatedDestinosIndexRouteImport.update({
    id: '/destinos/',
    path: '/destinos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinosNovoRoute =
  AuthenticatedDestinosNovoRouteImport.update({
    id: '/destinos/novo',
    path: '/destinos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacasIndexRoute =
  AuthenticatedPlacasIndexRouteImport.update({
    id: '/placas/',
    path: '/placas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacasNovaRoute = AuthenticatedPlacasNovaRouteImport.update({
  id: '/placas/nova',
  path: '/placas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacasCodeConfigurarRoute =
  AuthenticatedPlacasCodeConfigurarRouteImport.update({
    id: '/placas/$code/configurar',
    path: '/placas/$code/configurar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacasCodeQrRoute =
  AuthenticatedPlacasCodeQrRouteImport.update({
    id: '/placas/$code/qr',
    path: '/placas/$code/qr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ler-qr': typeof AuthenticatedLerQrRoute
  '/q/$code': typeof QCodeRoute
  '/destinos/novo': typeof AuthenticatedDestinosNovoRoute
  '/placas/nova': typeof AuthenticatedPlacasNovaRoute
  '/destinos/': typeof AuthenticatedDestinosIndexRoute
  '/placas/': typeof AuthenticatedPlacasIndexRoute
  '/placas/$code/configurar': typeof AuthenticatedPlacasCodeConfigurarRoute
  '/placas/$code/qr': typeof AuthenticatedPlacasCodeQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ler-qr': typeof AuthenticatedLerQrRoute
  '/q/$code': typeof QCodeRoute
  '/destinos/novo': typeof AuthenticatedDestinosNovoRoute
  '/placas/nova': typeof AuthenticatedPlacasNovaRoute
  '/destinos': typeof AuthenticatedDestinosIndexRoute
  '/placas': typeof AuthenticatedPlacasIndexRoute
  '/placas/$code/configurar': typeof AuthenticatedPlacasCodeConfigurarRoute
  '/placas/$code/qr': typeof AuthenticatedPlacasCodeQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ler-qr': typeof AuthenticatedLerQrRoute
  '/q/$code': typeof QCodeRoute
  '/_authenticated/destinos/novo': typeof AuthenticatedDestinosNovoRoute
  '/_authenticated/placas/nova': typeof AuthenticatedPlacasNovaRoute
  '/_authenticated/destinos/': typeof AuthenticatedDestinosIndexRoute
  '/_authenticated/placas/': typeof AuthenticatedPlacasIndexRoute
  '/_authenticated/placas/$code/configurar': typeof AuthenticatedPlacasCodeConfigurarRoute
  '/_authenticated/placas/$code/qr': typeof AuthenticatedPlacasCodeQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ler-qr'
    | '/q/$code'
    | '/destinos/novo'
    | '/placas/nova'
    | '/destinos/'
    | '/placas/'
    | '/placas/$code/configurar'
    | '/placas/$code/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ler-qr'
    | '/q/$code'
    | '/destinos/novo'
    | '/placas/nova'
    | '/destinos'
    | '/placas'
    | '/placas/$code/configurar'
    | '/placas/$code/qr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ler-qr'
    | '/q/$code'
    | '/_authenticated/destinos/novo'
    | '/_authenticated/placas/nova'
    | '/_authenticated/destinos/'
    | '/_authenticated/placas/'
    | '/_authenticated/placas/$code/configurar'
    | '/_authenticated/placas/$code/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QCodeRoute: typeof QCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ler-qr': {
      id: '/_authenticated/ler-qr'
      path: '/ler-qr'
      fullPath: '/ler-qr'
      preLoaderRoute: typeof AuthenticatedLerQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/destinos/': {
      id: '/_authenticated/destinos/'
      path: '/destinos'
      fullPath: '/destinos/'
      preLoaderRoute: typeof AuthenticatedDestinosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinos/novo': {
      id: '/_authenticated/destinos/novo'
      path: '/destinos/novo'
      fullPath: '/destinos/novo'
      preLoaderRoute: typeof AuthenticatedDestinosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placas/': {
      id: '/_authenticated/placas/'
      path: '/placas'
      fullPath: '/placas/'
      preLoaderRoute: typeof AuthenticatedPlacasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placas/nova': {
      id: '/_authenticated/placas/nova'
      path: '/placas/nova'
      fullPath: '/placas/nova'
      preLoaderRoute: typeof AuthenticatedPlacasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placas/$code/configurar': {
      id: '/_authenticated/placas/$code/configurar'
      path: '/placas/$code/configurar'
      fullPath: '/placas/$code/configurar'
      preLoaderRoute: typeof AuthenticatedPlacasCodeConfigurarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placas/$code/qr': {
      id: '/_authenticated/placas/$code/qr'
      path: '/placas/$code/qr'
      fullPath: '/placas/$code/qr'
      preLoaderRoute: typeof AuthenticatedPlacasCodeQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLerQrRoute: typeof AuthenticatedLerQrRoute
  AuthenticatedDestinosNovoRoute: typeof AuthenticatedDestinosNovoRoute
  AuthenticatedPlacasNovaRoute: typeof AuthenticatedPlacasNovaRoute
  AuthenticatedDestinosIndexRoute: typeof AuthenticatedDestinosIndexRoute
  AuthenticatedPlacasIndexRoute: typeof AuthenticatedPlacasIndexRoute
  AuthenticatedPlacasCodeConfigurarRoute: typeof AuthenticatedPlacasCodeConfigurarRoute
  AuthenticatedPlacasCodeQrRoute: typeof AuthenticatedPlacasCodeQrRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLerQrRoute: AuthenticatedLerQrRoute,
  AuthenticatedDestinosNovoRoute: AuthenticatedDestinosNovoRoute,
  AuthenticatedPlacasNovaRoute: AuthenticatedPlacasNovaRoute,
  AuthenticatedDestinosIndexRoute: AuthenticatedDestinosIndexRoute,
  AuthenticatedPlacasIndexRoute: AuthenticatedPlacasIndexRoute,
  AuthenticatedPlacasCodeConfigurarRoute:
    AuthenticatedPlacasCodeConfigurarRoute,
  AuthenticatedPlacasCodeQrRoute: AuthenticatedPlacasCodeQrRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  QCodeRoute: QCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
